[package]
name = "snowdiff"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.4"
crossterm = "0.29.0"
indexmap = "2.9.0"
ratatui = "0.29.0"
regex = "1.11.1"
similar = "2.7.0"
sqlparser = { version = "0.56.0", features = ["visitor"]}
